[
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": true,
    "single_hunk": true,
    "fit_TFix": true,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:159:8 Incompatible attribute type [8]: Attribute `id` declared in class `application_models.OwnConnection` has type `str` but is used as type `snowflake.Snowflake`.",
    "message": " Attribute `id` declared in class `application_models.OwnConnection` has type `str` but is used as type `snowflake.Snowflake`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 159,
    "warning_line": "        own_connection.id = snowflake.Snowflake(payload[\"id\"])",
    "min_patch": [
      {
        "hunk_fit_TFix": true,
        "inside_window": true,
        "delete_only": false,
        "has_suppression": false,
        "source_code": "        own_connection = application_models.OwnConnection()\n        own_connection.id = snowflake.Snowflake(payload[\"id\"])\n        own_connection.name = payload[\"name\"]\n        own_connection.type = payload[\"type\"]\n        own_connection.is_revoked = payload.get(\"revoked\")\n        own_connection.integrations = [\n",
        "source_code_len": 314,
        "target_code": "        own_connection = application_models.OwnConnection()\n        own_connection.id = payload[\"id\"]  # this is not a snowflake!\n        own_connection.name = payload[\"name\"]\n        own_connection.type = payload[\"type\"]\n        own_connection.is_revoked = payload[\"revoked\"]\n        own_connection.integrations = [\n",
        "target_code_len": 317,
        "diff_format": "@@ -158,6 +161,6 @@\n         own_connection = application_models.OwnConnection()\n-        own_connection.id = snowflake.Snowflake(payload[\"id\"])\n+        own_connection.id = payload[\"id\"]  # this is not a snowflake!\n         own_connection.name = payload[\"name\"]\n         own_connection.type = payload[\"type\"]\n-        own_connection.is_revoked = payload.get(\"revoked\")\n+        own_connection.is_revoked = payload[\"revoked\"]\n         own_connection.integrations = [\n",
        "source_code_with_indent": "        <IND>own_connection = application_models.OwnConnection()\n        own_connection.id = snowflake.Snowflake(payload[\"id\"])\n        own_connection.name = payload[\"name\"]\n        own_connection.type = payload[\"type\"]\n        own_connection.is_revoked = payload.get(\"revoked\")\n        own_connection.integrations = [\n",
        "source_code_with_indent_exact_match": true,
        "target_code_with_indent": "        <IND>own_connection = application_models.OwnConnection()\n        own_connection.id = payload[\"id\"]  # this is not a snowflake!\n        own_connection.name = payload[\"name\"]\n        own_connection.type = payload[\"type\"]\n        own_connection.is_revoked = payload[\"revoked\"]\n        own_connection.integrations = [\n",
        "target_code_with_indent_exact_match": true
      }
    ]
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:365:8 Incompatible attribute type [8]: Attribute `integrations` declared in class `audit_log_models.AuditLog` has type `typing.Mapping[snowflake.Snowflake, guild_models.Integration]` but is used as type `typing.Dict[snowflake.Snowflake, guild_models.PartialIntegration]`.",
    "message": " Attribute `integrations` declared in class `audit_log_models.AuditLog` has type `typing.Mapping[snowflake.Snowflake, guild_models.Integration]` but is used as type `typing.Dict[snowflake.Snowflake, guild_models.PartialIntegration]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 365,
    "warning_line": "        audit_log.integrations = {"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:754:8 Incompatible variable type [9]: user is declared to have type `typing.Union[undefined.UndefinedType, user_models.User]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " user is declared to have type `typing.Union[undefined.UndefinedType, user_models.User]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 754,
    "warning_line": "        user: typing.Union[undefined.UndefinedType, user_models.User] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:757:8 Incompatible attribute type [8]: Attribute `user` declared in class `guild_models.Member` has type `user_models.User` but is used as type `typing.Union[undefined.UndefinedType, user_models.User]`.",
    "message": " Attribute `user` declared in class `guild_models.Member` has type `user_models.User` but is used as type `typing.Union[undefined.UndefinedType, user_models.User]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 757,
    "warning_line": "        guild_member.user = user or self.deserialize_user(payload[\"user\"])"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:763:12 Incompatible attribute type [8]: Attribute `joined_at` declared in class `guild_models.Member` has type `typing.Union[datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " Attribute `joined_at` declared in class `guild_models.Member` has type `typing.Union[datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 763,
    "warning_line": "            guild_member.joined_at = undefined.UNDEFINED"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:771:8 Incompatible attribute type [8]: Attribute `premium_since` declared in class `guild_models.Member` has type `typing.Union[None, datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], datetime.datetime]`.",
    "message": " Attribute `premium_since` declared in class `guild_models.Member` has type `typing.Union[None, datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], datetime.datetime]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 771,
    "warning_line": "        guild_member.premium_since = premium_since"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1151:8 Incompatible attribute type [8]: Attribute `flags` declared in class `user_models.PartialUser` has type `typing.Union[undefined.UndefinedType, user_models.UserFlag]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], user_models.UserFlag]`.",
    "message": " Attribute `flags` declared in class `user_models.PartialUser` has type `typing.Union[undefined.UndefinedType, user_models.UserFlag]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], user_models.UserFlag]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1151,
    "warning_line": "        user.flags = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1540:8 Incompatible attribute type [8]: Attribute `channel_id` declared in class `message_events.UpdateMessage` has type `snowflake.Snowflake` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], snowflake.Snowflake]`.",
    "message": " Attribute `channel_id` declared in class `message_events.UpdateMessage` has type `snowflake.Snowflake` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], snowflake.Snowflake]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1540,
    "warning_line": "        updated_message.channel_id = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1543:8 Incompatible attribute type [8]: Attribute `guild_id` declared in class `message_events.UpdateMessage` has type `typing.Union[snowflake.Snowflake, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], snowflake.Snowflake]`.",
    "message": " Attribute `guild_id` declared in class `message_events.UpdateMessage` has type `typing.Union[snowflake.Snowflake, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], snowflake.Snowflake]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1543,
    "warning_line": "        updated_message.guild_id = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1546:8 Incompatible attribute type [8]: Attribute `author` declared in class `message_events.UpdateMessage` has type `typing.Union[undefined.UndefinedType, user_models.User]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], user_models.User]`.",
    "message": " Attribute `author` declared in class `message_events.UpdateMessage` has type `typing.Union[undefined.UndefinedType, user_models.User]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], user_models.User]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1546,
    "warning_line": "        updated_message.author = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1550:8 Incompatible attribute type [8]: Attribute `member` declared in class `message_events.UpdateMessage` has type `typing.Union[guild_models.Member, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], guild_models.Member]`.",
    "message": " Attribute `member` declared in class `message_events.UpdateMessage` has type `typing.Union[guild_models.Member, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], guild_models.Member]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1550,
    "warning_line": "        updated_message.member = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1556:8 Incompatible attribute type [8]: Attribute `timestamp` declared in class `message_events.UpdateMessage` has type `typing.Union[datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], datetime.datetime]`.",
    "message": " Attribute `timestamp` declared in class `message_events.UpdateMessage` has type `typing.Union[datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], datetime.datetime]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1556,
    "warning_line": "        updated_message.timestamp = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1566:8 Incompatible attribute type [8]: Attribute `edited_timestamp` declared in class `message_events.UpdateMessage` has type `typing.Union[None, datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], datetime.datetime]`.",
    "message": " Attribute `edited_timestamp` declared in class `message_events.UpdateMessage` has type `typing.Union[None, datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], datetime.datetime]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1566,
    "warning_line": "        updated_message.edited_timestamp = edited_timestamp"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1572:8 Incompatible attribute type [8]: Attribute `user_mentions` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Set[snowflake.Snowflake], undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], typing.Set[snowflake.Snowflake]]`.",
    "message": " Attribute `user_mentions` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Set[snowflake.Snowflake], undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], typing.Set[snowflake.Snowflake]]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1572,
    "warning_line": "        updated_message.user_mentions = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1577:8 Incompatible attribute type [8]: Attribute `role_mentions` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Set[snowflake.Snowflake], undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], typing.Set[snowflake.Snowflake]]`.",
    "message": " Attribute `role_mentions` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Set[snowflake.Snowflake], undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], typing.Set[snowflake.Snowflake]]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1577,
    "warning_line": "        updated_message.role_mentions = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1582:8 Incompatible attribute type [8]: Attribute `channel_mentions` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Set[snowflake.Snowflake], undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], typing.Set[snowflake.Snowflake]]`.",
    "message": " Attribute `channel_mentions` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Set[snowflake.Snowflake], undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], typing.Set[snowflake.Snowflake]]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1582,
    "warning_line": "        updated_message.channel_mentions = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1602:12 Incompatible attribute type [8]: Attribute `attachments` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Sequence[message_models.Attachment], undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " Attribute `attachments` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Sequence[message_models.Attachment], undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1602,
    "warning_line": "            updated_message.attachments = undefined.UNDEFINED"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1604:8 Incompatible attribute type [8]: Attribute `embeds` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Sequence[embed_models.Embed], undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], typing.List[embed_models.Embed]]`.",
    "message": " Attribute `embeds` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Sequence[embed_models.Embed], undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], typing.List[embed_models.Embed]]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1604,
    "warning_line": "        updated_message.embeds = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1620:12 Incompatible attribute type [8]: Attribute `reactions` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Sequence[message_models.Reaction], undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " Attribute `reactions` declared in class `message_events.UpdateMessage` has type `typing.Union[typing.Sequence[message_models.Reaction], undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1620,
    "warning_line": "            updated_message.reactions = undefined.UNDEFINED"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1623:8 Incompatible attribute type [8]: Attribute `webhook_id` declared in class `message_events.UpdateMessage` has type `typing.Union[snowflake.Snowflake, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], snowflake.Snowflake]`.",
    "message": " Attribute `webhook_id` declared in class `message_events.UpdateMessage` has type `typing.Union[snowflake.Snowflake, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], snowflake.Snowflake]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1623,
    "warning_line": "        updated_message.webhook_id = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1627:8 Incompatible attribute type [8]: Attribute `type` declared in class `message_events.UpdateMessage` has type `typing.Union[message_models.MessageType, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], message_models.MessageType]`.",
    "message": " Attribute `type` declared in class `message_events.UpdateMessage` has type `typing.Union[message_models.MessageType, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], message_models.MessageType]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1627,
    "warning_line": "        updated_message.type = message_models.MessageType(payload[\"type\"]) if \"type\" in payload else undefined.UNDEFINED"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1636:12 Incompatible attribute type [8]: Attribute `activity` declared in class `message_events.UpdateMessage` has type `typing.Union[message_models.MessageActivity, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " Attribute `activity` declared in class `message_events.UpdateMessage` has type `typing.Union[message_models.MessageActivity, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1636,
    "warning_line": "            updated_message.activity = undefined.UNDEFINED"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1638:8 Incompatible attribute type [8]: Attribute `application` declared in class `message_events.UpdateMessage` has type `typing.Optional[application_models.Application]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], application_models.Application]`.",
    "message": " Attribute `application` declared in class `message_events.UpdateMessage` has type `typing.Optional[application_models.Application]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], application_models.Application]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1638,
    "warning_line": "        updated_message.application = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1653:12 Incompatible attribute type [8]: Attribute `message_reference` declared in class `message_events.UpdateMessage` has type `typing.Union[message_models.MessageCrosspost, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " Attribute `message_reference` declared in class `message_events.UpdateMessage` has type `typing.Union[message_models.MessageCrosspost, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1653,
    "warning_line": "            updated_message.message_reference = undefined.UNDEFINED"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/entity_factory.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/entity_factory.py",
    "file_hunks_size": 6,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/entity_factory.py:1656:8 Incompatible attribute type [8]: Attribute `flags` declared in class `message_events.UpdateMessage` has type `typing.Union[message_models.MessageFlag, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], message_models.MessageFlag]`.",
    "message": " Attribute `flags` declared in class `message_events.UpdateMessage` has type `typing.Union[message_models.MessageFlag, undefined.UndefinedType]` but is used as type `typing.Union[typing.Final[undefined.UndefinedType], message_models.MessageFlag]`.",
    "rule_id": "Incompatible attribute type [8]",
    "warning_line_no": 1656,
    "warning_line": "        updated_message.flags = ("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/event_manager_core.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/event_manager_core.py",
    "file_hunks_size": 14,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/event_manager_core.py:101:47 Incompatible parameter type [6]: Expected `typing.Union[typing.Callable[[typing.Any], None], typing.Callable[[typing.Any], typing.Coroutine[None, typing.Any, None]]]` for 1st positional only parameter to call `typing.MutableSequence.append` but got `typing.Callable[[Variable[_EventT (bound to base.HikariEvent)](covariant)], typing.Optional[typing.Coroutine[None, typing.Any, None]]]`.",
    "message": " Expected `typing.Union[typing.Callable[[typing.Any], None], typing.Callable[[typing.Any], typing.Coroutine[None, typing.Any, None]]]` for 1st positional only parameter to call `typing.MutableSequence.append` but got `typing.Callable[[Variable[_EventT (bound to base.HikariEvent)](covariant)], typing.Optional[typing.Coroutine[None, typing.Any, None]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 101,
    "warning_line": "            self._listeners[event_type].append(callback)"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/event_manager_core.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/event_manager_core.py",
    "file_hunks_size": 14,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/event_manager_core.py:116:47 Incompatible parameter type [6]: Expected `typing.Union[typing.Callable[[typing.Any], None], typing.Callable[[typing.Any], typing.Coroutine[None, typing.Any, None]]]` for 1st positional only parameter to call `typing.MutableSequence.remove` but got `typing.Callable[[Variable[_EventT (bound to base.HikariEvent)](covariant)], typing.Optional[typing.Coroutine[None, typing.Any, None]]]`.",
    "message": " Expected `typing.Union[typing.Callable[[typing.Any], None], typing.Callable[[typing.Any], typing.Coroutine[None, typing.Any, None]]]` for 1st positional only parameter to call `typing.MutableSequence.remove` but got `typing.Callable[[Variable[_EventT (bound to base.HikariEvent)](covariant)], typing.Optional[typing.Coroutine[None, typing.Any, None]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 116,
    "warning_line": "            self._listeners[event_type].remove(callback)"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/event_manager_core.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/event_manager_core.py",
    "file_hunks_size": 14,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/event_manager_core.py:121:14 Incompatible variable type [9]: event_type is declared to have type `typing.Union[typing.Type[Variable[_EventT (bound to base.HikariEvent)](covariant)], undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " event_type is declared to have type `typing.Union[typing.Type[Variable[_EventT (bound to base.HikariEvent)](covariant)], undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 121,
    "warning_line": "        self, event_type: typing.Union[undefined.UndefinedType, typing.Type[_EventT]] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/event_manager_core.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/event_manager_core.py",
    "file_hunks_size": 14,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/event_manager_core.py:190:84 Incompatible parameter type [6]: Expected `typing.Callable[[base.HikariEvent], typing.Awaitable[None]]` for 3rd parameter `callback` to call `other.ExceptionEvent.__init__` but got `typing.Union[typing.Callable[[typing.Any], None], typing.Callable[[typing.Any], typing.Coroutine[None, typing.Any, None]]]`.",
    "message": " Expected `typing.Callable[[base.HikariEvent], typing.Awaitable[None]]` for 3rd parameter `callback` to call `other.ExceptionEvent.__init__` but got `typing.Union[typing.Callable[[typing.Any], None], typing.Callable[[typing.Any], typing.Coroutine[None, typing.Any, None]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 190,
    "warning_line": "                await self.dispatch(other.ExceptionEvent(exception=ex, event=event, callback=callback))"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/gateway_zookeeper.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/gateway_zookeeper.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/gateway_zookeeper.py:134:8 Incompatible variable type [9]: initial_activity is declared to have type `typing.Union[None, presences.Activity, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " initial_activity is declared to have type `typing.Union[None, presences.Activity, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 134,
    "warning_line": "        initial_activity: typing.Union[undefined.UndefinedType, presences.Activity, None] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/gateway_zookeeper.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/gateway_zookeeper.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/gateway_zookeeper.py:135:8 Incompatible variable type [9]: initial_idle_since is declared to have type `typing.Union[None, datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " initial_idle_since is declared to have type `typing.Union[None, datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 135,
    "warning_line": "        initial_idle_since: typing.Union[undefined.UndefinedType, datetime.datetime, None] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/gateway_zookeeper.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/gateway_zookeeper.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/gateway_zookeeper.py:136:8 Incompatible variable type [9]: initial_is_afk is declared to have type `typing.Union[bool, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " initial_is_afk is declared to have type `typing.Union[bool, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 136,
    "warning_line": "        initial_is_afk: typing.Union[undefined.UndefinedType, bool] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/gateway_zookeeper.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/gateway_zookeeper.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/gateway_zookeeper.py:137:8 Incompatible variable type [9]: initial_status is declared to have type `typing.Union[presences.Status, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " initial_status is declared to have type `typing.Union[presences.Status, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 137,
    "warning_line": "        initial_status: typing.Union[undefined.UndefinedType, presences.Status] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/gateway_zookeeper.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/gateway_zookeeper.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/gateway_zookeeper.py:291:4 Inconsistent override [14]: `hikari.impl.gateway_zookeeper.AbstractGatewayZookeeper.update_presence` overrides method defined in `app_.IGatewayZookeeper` inconsistently. Parameter of type `typing.Union[datetime.datetime, undefined.UndefinedType]` is not a supertype of the overridden parameter `typing.Union[None, datetime.datetime, undefined.UndefinedType]`.",
    "message": " `hikari.impl.gateway_zookeeper.AbstractGatewayZookeeper.update_presence` overrides method defined in `app_.IGatewayZookeeper` inconsistently. Parameter of type `typing.Union[datetime.datetime, undefined.UndefinedType]` is not a supertype of the overridden parameter `typing.Union[None, datetime.datetime, undefined.UndefinedType]`.",
    "rule_id": "Inconsistent override [14]",
    "warning_line_no": 291,
    "warning_line": "    async def update_presence("
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/gateway_zookeeper.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/gateway_zookeeper.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/gateway_zookeeper.py:294:8 Incompatible variable type [9]: status is declared to have type `typing.Union[presences.Status, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " status is declared to have type `typing.Union[presences.Status, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 294,
    "warning_line": "        status: typing.Union[undefined.UndefinedType, presences.Status] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/gateway_zookeeper.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/gateway_zookeeper.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/gateway_zookeeper.py:295:8 Incompatible variable type [9]: activity is declared to have type `typing.Union[None, presences.Activity, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " activity is declared to have type `typing.Union[None, presences.Activity, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 295,
    "warning_line": "        activity: typing.Union[undefined.UndefinedType, presences.Activity, None] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/gateway_zookeeper.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/gateway_zookeeper.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/gateway_zookeeper.py:296:8 Incompatible variable type [9]: idle_since is declared to have type `typing.Union[datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " idle_since is declared to have type `typing.Union[datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 296,
    "warning_line": "        idle_since: typing.Union[undefined.UndefinedType, datetime.datetime] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/gateway_zookeeper.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/gateway_zookeeper.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/gateway_zookeeper.py:297:8 Incompatible variable type [9]: is_afk is declared to have type `typing.Union[bool, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " is_afk is declared to have type `typing.Union[bool, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 297,
    "warning_line": "        is_afk: typing.Union[undefined.UndefinedType, bool] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/rest_app.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/rest_app.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/rest_app.py:76:8 Incompatible variable type [9]: config is declared to have type `typing.Union[http_settings_.HTTPSettings, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " config is declared to have type `typing.Union[http_settings_.HTTPSettings, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 76,
    "warning_line": "        config: typing.Union[undefined.UndefinedType, http_settings_.HTTPSettings] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/rest_app.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/rest_app.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/rest_app.py:78:8 Incompatible variable type [9]: token is declared to have type `typing.Union[str, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " token is declared to have type `typing.Union[str, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 78,
    "warning_line": "        token: typing.Union[undefined.UndefinedType, str] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/rest_app.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/rest_app.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/rest_app.py:79:8 Incompatible variable type [9]: token_type is declared to have type `typing.Union[str, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " token_type is declared to have type `typing.Union[str, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 79,
    "warning_line": "        token_type: typing.Union[undefined.UndefinedType, str] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/rest_app.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/rest_app.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/rest_app.py:80:8 Incompatible variable type [9]: url is declared to have type `typing.Union[str, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "message": " url is declared to have type `typing.Union[str, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 80,
    "warning_line": "        url: typing.Union[undefined.UndefinedType, str] = undefined.UNDEFINED,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/rest_app.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/rest_app.py",
    "file_hunks_size": 1,
    "min_patch_found": true,
    "single_hunk": true,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/rest_app.py:83:23 Unbound name [10]: Name `reflect` is used but not defined in the current scope.",
    "message": " Name `reflect` is used but not defined in the current scope.",
    "rule_id": "Unbound name [10]",
    "warning_line_no": 83,
    "warning_line": "        self._logger = reflect.get_logger(self)",
    "min_patch": [
      {
        "hunk_fit_TFix": false,
        "inside_window": false,
        "delete_only": false,
        "has_suppression": false,
        "source_code": "from hikari.net import rest as rest_\nfrom hikari.utilities import undefined\n",
        "source_code_len": 76,
        "target_code": "from hikari.net import rest as rest_\nfrom hikari.utilities import reflect\nfrom hikari.utilities import undefined\n",
        "target_code_len": 113,
        "diff_format": "@@ -37,2 +37,3 @@\n from hikari.net import rest as rest_\n+from hikari.utilities import reflect\n from hikari.utilities import undefined\n",
        "source_code_with_indent": "from hikari.net import rest as rest_\nfrom hikari.utilities import undefined\n",
        "source_code_with_indent_exact_match": true,
        "target_code_with_indent": "from hikari.net import rest as rest_\nfrom hikari.utilities import reflect\nfrom hikari.utilities import undefined\n",
        "target_code_with_indent_exact_match": true
      }
    ]
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/impl/rest_app.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/impl/rest_app.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/impl/rest_app.py:88:22 Incompatible parameter type [6]: Expected `http_settings_.HTTPSettings` for 2nd parameter `config` to call `rest_.REST.__init__` but got `typing.Union[http_settings_.HTTPSettings, undefined.UndefinedType]`.",
    "message": " Expected `http_settings_.HTTPSettings` for 2nd parameter `config` to call `rest_.REST.__init__` but got `typing.Union[http_settings_.HTTPSettings, undefined.UndefinedType]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 88,
    "warning_line": "            app=self, config=config, debug=debug, token=token, token_type=token_type, rest_url=url, version=version,"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:164:8 Incompatible variable type [9]: initial_activity is declared to have type `typing.Union[None, presences.Activity, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:165:8 Incompatible variable type [9]: initial_idle_since is declared to have type `typing.Union[None, datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:166:8 Incompatible variable type [9]: initial_is_afk is declared to have type `typing.Union[bool, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:167:8 Incompatible variable type [9]: initial_status is declared to have type `typing.Union[presences.Status, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:386:8 Incompatible variable type [9]: idle_since is declared to have type `typing.Union[None, datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:387:8 Incompatible variable type [9]: is_afk is declared to have type `typing.Union[bool, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:388:8 Incompatible variable type [9]: activity is declared to have type `typing.Union[None, presences.Activity, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:389:8 Incompatible variable type [9]: status is declared to have type `typing.Union[presences.Status, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:669:8 Incompatible variable type [9]: idle_since is declared to have type `typing.Union[None, datetime.datetime, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:670:8 Incompatible variable type [9]: is_afk is declared to have type `typing.Union[bool, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:671:8 Incompatible variable type [9]: status is declared to have type `typing.Union[presences.Status, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hikari-py/hikari",
    "commit": "0649b1e99f0bec1862c99920f04395e6c32bc02e",
    "filename": "hikari/net/gateway.py",
    "min_patch_found": false,
    "full_warning_msg": "hikari/net/gateway.py:672:8 Incompatible variable type [9]: activity is declared to have type `typing.Union[None, presences.Activity, undefined.UndefinedType]` but is used as type `typing.Final[undefined.UndefinedType]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  }
]