[
  {
    "project": "angr/angr",
    "commit": "f8a52691c00135351abac78e1adf56a2ebeb69b5",
    "filename": "angr/knowledge_plugins/key_definitions/dataset.py",
    "min_patch_found": false,
    "full_warning_msg": "angr/knowledge_plugins/key_definitions/dataset.py:32:27 Unsupported operand [58]: `<<` is not supported for operand types `int` and `Union[UnknownSize, int]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/angr-angr/angr/knowledge_plugins/key_definitions/dataset.py'",
    "dd_fail": true
  },
  {
    "project": "angr/angr",
    "commit": "f8a52691c00135351abac78e1adf56a2ebeb69b5",
    "filename": "angr/knowledge_plugins/key_definitions/dataset.py",
    "min_patch_found": false,
    "full_warning_msg": "angr/knowledge_plugins/key_definitions/dataset.py:210:8 Incompatible return type [7]: Expected `Tuple[int, UnknownSize]` but got `UnknownSize`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/angr-angr/angr/knowledge_plugins/key_definitions/dataset.py'",
    "dd_fail": true
  },
  {
    "project": "angr/angr",
    "commit": "f8a52691c00135351abac78e1adf56a2ebeb69b5",
    "filename": "angr/knowledge_plugins/key_definitions/dataset.py",
    "min_patch_found": false,
    "full_warning_msg": "angr/knowledge_plugins/key_definitions/dataset.py:211:4 Incompatible return type [7]: Expected `Tuple[int, UnknownSize]` but got `Union[UnknownSize, int]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/angr-angr/angr/knowledge_plugins/key_definitions/dataset.py'",
    "dd_fail": true
  },
  {
    "project": "angr/angr",
    "commit": "f8a52691c00135351abac78e1adf56a2ebeb69b5",
    "filename": "angr/knowledge_plugins/key_definitions/dataset.py",
    "min_patch_found": false,
    "full_warning_msg": "angr/knowledge_plugins/key_definitions/dataset.py:229:28 Incompatible parameter type [6]: Expected `Union[UnknownSize, int]` for 2nd positional only parameter to call `DataSet.__init__` but got `Tuple[int, UnknownSize]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/angr-angr/angr/knowledge_plugins/key_definitions/dataset.py'",
    "dd_fail": true
  }
]