[
  {
    "project": "quantumblacklabs/causalnex",
    "commit": "b89c6d307db2ab35ee7b1d3e805832255b2b3e7d",
    "filename": "causalnex/inference/inference.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/quantumblacklabs-causalnex/causalnex/inference/inference.py",
    "file_hunks_size": 19,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "causalnex/inference/inference.py:132:14 Incompatible variable type [9]: observations is declared to have type `Dict[str, Hashable]` but is used as type `None`.",
    "message": " observations is declared to have type `Dict[str, Hashable]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 132,
    "warning_line": "        self, observations: Dict[str, Hashable] = None"
  },
  {
    "project": "quantumblacklabs/causalnex",
    "commit": "b89c6d307db2ab35ee7b1d3e805832255b2b3e7d",
    "filename": "causalnex/inference/inference.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/quantumblacklabs-causalnex/causalnex/inference/inference.py",
    "file_hunks_size": 19,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "causalnex/inference/inference.py:163:8 Incompatible variable type [9]: observations is declared to have type `Union[Dict[str, Hashable], List[Dict[str, Hashable]]]` but is used as type `None`.",
    "message": " observations is declared to have type `Union[Dict[str, Hashable], List[Dict[str, Hashable]]]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 163,
    "warning_line": "        observations: Union[Dict[str, Hashable], List[Dict[str, Hashable]]] = None,"
  },
  {
    "project": "quantumblacklabs/causalnex",
    "commit": "b89c6d307db2ab35ee7b1d3e805832255b2b3e7d",
    "filename": "causalnex/inference/inference.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/quantumblacklabs-causalnex/causalnex/inference/inference.py",
    "file_hunks_size": 19,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "causalnex/inference/inference.py:165:8 Incompatible variable type [9]: num_cores is declared to have type `int` but is used as type `None`.",
    "message": " num_cores is declared to have type `int` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 165,
    "warning_line": "        num_cores: int = None,"
  },
  {
    "project": "quantumblacklabs/causalnex",
    "commit": "b89c6d307db2ab35ee7b1d3e805832255b2b3e7d",
    "filename": "causalnex/inference/inference.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/quantumblacklabs-causalnex/causalnex/inference/inference.py",
    "file_hunks_size": 19,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "causalnex/inference/inference.py:182:38 Incompatible parameter type [6]: Expected `Dict[str, Hashable]` for 1st positional only parameter to call `InferenceEngine._single_query` but got `Union[Dict[str, Hashable], List[Dict[str, Hashable]]]`.",
    "message": " Expected `Dict[str, Hashable]` for 1st positional only parameter to call `InferenceEngine._single_query` but got `Union[Dict[str, Hashable], List[Dict[str, Hashable]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 182,
    "warning_line": "            return self._single_query(observations)"
  },
  {
    "project": "quantumblacklabs/causalnex",
    "commit": "b89c6d307db2ab35ee7b1d3e805832255b2b3e7d",
    "filename": "causalnex/inference/inference.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/quantumblacklabs-causalnex/causalnex/inference/inference.py",
    "file_hunks_size": 19,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "causalnex/inference/inference.py:257:23 Incompatible parameter type [6]: Expected `Dict[Hashable, float]` for 2nd positional only parameter to call `InferenceEngine._do` but got `Union[Dict[typing.Any, float], Hashable]`.",
    "message": " Expected `Dict[Hashable, float]` for 2nd positional only parameter to call `InferenceEngine._do` but got `Union[Dict[typing.Any, float], Hashable]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 257,
    "warning_line": "        self._do(node, state)"
  },
  {
    "project": "quantumblacklabs/causalnex",
    "commit": "b89c6d307db2ab35ee7b1d3e805832255b2b3e7d",
    "filename": "causalnex/inference/inference.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/quantumblacklabs-causalnex/causalnex/inference/inference.py",
    "file_hunks_size": 19,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "causalnex/inference/inference.py:338:44 Incompatible parameter type [6]: Expected `types.FrameType` for 1st positional only parameter to call `inspect.getargvalues` but got `typing.Optional[types.FrameType]`.",
    "message": " Expected `types.FrameType` for 1st positional only parameter to call `inspect.getargvalues` but got `typing.Optional[types.FrameType]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 338,
    "warning_line": "            arg_spec = inspect.getargvalues(inspect.currentframe())"
  }
]