[
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/datetime.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/datetime.py:42:30 Incompatible parameter type [6]: Expected `None` for 1st positional only parameter to call `list.append` but got `int`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/datetime.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/datetime.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/datetime.py:43:11 Unsupported operand [58]: `+` is not supported for operand types `int` and `typing.Optional[int]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/datetime.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/datetime.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/datetime.py:1307:16 Unsupported operand [58]: `+` is not supported for operand types `typing.Union[typing.Iterable[str], str]` and `typing.Tuple[str, str, str, str, str]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/datetime.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/datetime.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/datetime.py:1819:4 Inconsistent override [15]: `__slots__` overrides attribute defined in `tzinfo` inconsistently. Type `typing.Tuple[str, str]` is not a subtype of the overridden attribute `typing.Tuple[]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/datetime.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/email/_policybase.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/email/_policybase.py:119:13 Invalid type [31]: Expression `future.utils.with_metaclass(abc.ABCMeta, lib.future.backports.email._policybase._PolicyBase)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/email/_policybase.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/email/generator.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/email/generator.py:397:4 Inconsistent override [15]: `_encoded_EMPTY` overrides attribute defined in `Generator` inconsistently. Type `bytes` is not a subtype of the overridden attribute `str`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/email/generator.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/misc.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/misc.py:235:4 Incompatible attribute type [8]: Attribute `keys` declared in class `OrderedDict` has type `typing.Callable(OrderedDict.keys)[[Named(self, OrderedDict[Variable[collections._KT], Variable[collections._VT]])], collections._OrderedDictKeysView[Variable[collections._KT]]]` but is used as type `typing.Callable(typing.Mapping.keys)[[Named(self, typing.Mapping[typing.Any, typing.Any])], typing.AbstractSet[typing.Any]]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/misc.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/misc.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/misc.py:236:4 Incompatible attribute type [8]: Attribute `values` declared in class `OrderedDict` has type `typing.Callable(OrderedDict.values)[[Named(self, OrderedDict[Variable[collections._KT], Variable[collections._VT]])], collections._OrderedDictValuesView[Variable[collections._VT]]]` but is used as type `typing.Callable(typing.Mapping.values)[[Named(self, typing.Mapping[typing.Any, typing.Any])], typing.ValuesView[typing.Any]]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/misc.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/misc.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/misc.py:237:4 Incompatible attribute type [8]: Attribute `items` declared in class `OrderedDict` has type `typing.Callable(OrderedDict.items)[[Named(self, OrderedDict[Variable[collections._KT], Variable[collections._VT]])], collections._OrderedDictItemsView[Variable[collections._KT], Variable[collections._VT]]]` but is used as type `typing.Callable(typing.Mapping.items)[[Named(self, typing.Mapping[typing.Any, typing.Any])], typing.AbstractSet[typing.Tuple[typing.Any, typing.Any]]]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/misc.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/xmlrpc/client.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/xmlrpc/client.py:138:0 Incompatible variable type [9]: base64.encodebytes is declared to have type `typing.Callable(base64.encodebytes)[[Named(s, bytes)], bytes]` but is used as type `typing.Callable(base64.encodestring)[[Named(s, bytes)], bytes]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/xmlrpc/client.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/xmlrpc/client.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/xmlrpc/client.py:139:0 Incompatible variable type [9]: base64.decodebytes is declared to have type `typing.Callable(base64.decodebytes)[[Named(s, bytes)], bytes]` but is used as type `typing.Callable(base64.decodestring)[[Named(s, bytes)], bytes]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/xmlrpc/client.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/backports/xmlrpc/client.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/backports/xmlrpc/client.py:1078:26 Invalid type [31]: Expression `$local_lib?future?backports?xmlrpc?client$gzip.GzipFile if $local_lib?future?backports?xmlrpc?client$gzip else object` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/backports/xmlrpc/client.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/builtins/misc.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/builtins/misc.py:57:12 Unbound name [10]: Name `raw_input` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/builtins/misc.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/moves/itertools.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/moves/itertools.py:5:18 Unbound name [10]: Name `izip_longest` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/moves/itertools.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/moves/itertools.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/moves/itertools.py:6:18 Unbound name [10]: Name `ifilterfalse` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/moves/itertools.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/types/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/types/__init__.py:250:16 Unbound name [10]: Name `long` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/types/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/types/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/types/__init__.py:255:16 Unbound name [10]: Name `unicode` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/types/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/types/newbytes.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/types/newbytes.py:40:15 Invalid type [31]: Expression `future.utils.with_metaclass(lib.future.types.newbytes.BaseNewBytes, $local_lib?future?types?newbytes$_builtin_bytes)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/types/newbytes.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/types/newdict.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/types/newdict.py:37:14 Invalid type [31]: Expression `future.utils.with_metaclass(lib.future.types.newdict.BaseNewDict, $local_lib?future?types?newdict$_builtin_dict)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/types/newdict.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/types/newint.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/types/newint.py:31:13 Invalid type [31]: Expression `future.utils.with_metaclass(lib.future.types.newint.BaseNewInt, $local_lib?future?types?newint$long)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/types/newint.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/types/newlist.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/types/newlist.py:34:14 Invalid type [31]: Expression `future.utils.with_metaclass(lib.future.types.newlist.BaseNewList, $local_lib?future?types?newlist$_builtin_list)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/types/newlist.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/types/newstr.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/types/newstr.py:64:13 Invalid type [31]: Expression `future.utils.with_metaclass(lib.future.types.newstr.BaseNewStr, $local_lib?future?types?newstr$unicode)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/types/newstr.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/utils/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/utils/__init__.py:168:19 Unbound name [10]: Name `basestring` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/utils/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/utils/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/utils/__init__.py:169:26 Unbound name [10]: Name `long` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/utils/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/utils/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/utils/__init__.py:171:16 Unbound name [10]: Name `unicode` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/utils/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/future/utils/surrogateescape.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/future/utils/surrogateescape.py:37:14 Unbound name [10]: Name `unichr` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/future/utils/surrogateescape.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/http/client.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/http/client.py:4:7 Unsupported operand [58]: `<` is not supported for operand types `typing.Union[int, str]` and `int`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/http/client.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/http/cookiejar.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/http/cookiejar.py:4:7 Unsupported operand [58]: `<` is not supported for operand types `typing.Union[int, str]` and `int`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/http/cookiejar.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/http/cookies.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/http/cookies.py:4:7 Unsupported operand [58]: `<` is not supported for operand types `typing.Union[int, str]` and `int`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/http/cookies.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/http/server.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/http/server.py:4:7 Unsupported operand [58]: `<` is not supported for operand types `typing.Union[int, str]` and `int`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SickChill-SickChill/lib/http/server.py'",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/libgrowl/gntp_bridge.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/libgrowl/gntp_bridge.py:66:0 Unbound name [10]: Name `GNTPRegister` is used but not defined in the current scope.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "SickChill/SickChill",
    "commit": "90fdf11ea3972eb600337a4aace40c7affa8d931",
    "filename": "lib/libgrowl/gntp_bridge.py",
    "min_patch_found": false,
    "full_warning_msg": "lib/libgrowl/gntp_bridge.py:67:0 Unbound name [10]: Name `GNTPNotice` is used but not defined in the current scope.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  }
]