[
  {
    "project": "ilius/pyglossary",
    "commit": "0db440875ddae595c5cef0d6f35ec2ea4fc8d4fc",
    "filename": "pyglossary/exir.py",
    "min_patch_found": false,
    "full_warning_msg": "pyglossary/exir.py:6:12 Unbound name [10]: Name `Entity` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/ilius-pyglossary/pyglossary/exir.py'",
    "dd_fail": true
  },
  {
    "project": "ilius/pyglossary",
    "commit": "0db440875ddae595c5cef0d6f35ec2ea4fc8d4fc",
    "filename": "pyglossary/exir.py",
    "min_patch_found": false,
    "full_warning_msg": "pyglossary/exir.py:7:1 Unbound name [10]: Name `has_field` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/ilius-pyglossary/pyglossary/exir.py'",
    "dd_fail": true
  },
  {
    "project": "ilius/pyglossary",
    "commit": "0db440875ddae595c5cef0d6f35ec2ea4fc8d4fc",
    "filename": "pyglossary/exir.py",
    "min_patch_found": false,
    "full_warning_msg": "pyglossary/exir.py:7:19 Unbound name [10]: Name `Integer` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/ilius-pyglossary/pyglossary/exir.py'",
    "dd_fail": true
  },
  {
    "project": "ilius/pyglossary",
    "commit": "0db440875ddae595c5cef0d6f35ec2ea4fc8d4fc",
    "filename": "pyglossary/exir.py",
    "min_patch_found": false,
    "full_warning_msg": "pyglossary/exir.py:8:20 Unbound name [10]: Name `Unicode` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/ilius-pyglossary/pyglossary/exir.py'",
    "dd_fail": true
  },
  {
    "project": "ilius/pyglossary",
    "commit": "0db440875ddae595c5cef0d6f35ec2ea4fc8d4fc",
    "filename": "pyglossary/exir.py",
    "min_patch_found": false,
    "full_warning_msg": "pyglossary/exir.py:12:0 Unbound name [10]: Name `setup_all` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/ilius-pyglossary/pyglossary/exir.py'",
    "dd_fail": true
  },
  {
    "project": "ilius/pyglossary",
    "commit": "0db440875ddae595c5cef0d6f35ec2ea4fc8d4fc",
    "filename": "pyglossary/exir.py",
    "min_patch_found": false,
    "full_warning_msg": "pyglossary/exir.py:15:14 Unbound name [10]: Name `SessionContext` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/ilius-pyglossary/pyglossary/exir.py'",
    "dd_fail": true
  }
]