[
  {
    "project": "pyccel/pyccel",
    "commit": "40aab822dfedd645d5d611d7e7e16ef9121409fc",
    "filename": "tests/errors/semantic/ex1.py",
    "min_patch_found": false,
    "full_warning_msg": "tests/errors/semantic/ex1.py:5:9 Unbound name [10]: Name `a` is used but not defined in the current scope.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "pyccel/pyccel",
    "commit": "40aab822dfedd645d5d611d7e7e16ef9121409fc",
    "filename": "tests/errors/semantic/ex1.py",
    "min_patch_found": false,
    "full_warning_msg": "tests/errors/semantic/ex1.py:6:5 Unbound name [10]: Name `f` is used but not defined in the current scope.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "pyccel/pyccel",
    "commit": "40aab822dfedd645d5d611d7e7e16ef9121409fc",
    "filename": "tests/errors/semantic/ex2.py",
    "min_patch_found": false,
    "full_warning_msg": "tests/errors/semantic/ex2.py:2:5 Unbound name [10]: Name `y` is used but not defined in the current scope.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "pyccel/pyccel",
    "commit": "40aab822dfedd645d5d611d7e7e16ef9121409fc",
    "filename": "tests/errors/semantic/ex4.py",
    "min_patch_found": false,
    "full_warning_msg": "tests/errors/semantic/ex4.py:1:0 Unbound name [10]: Name `x` is used but not defined in the current scope.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "pyccel/pyccel",
    "commit": "40aab822dfedd645d5d611d7e7e16ef9121409fc",
    "filename": "tests/errors/semantic/ex4.py",
    "min_patch_found": false,
    "full_warning_msg": "tests/errors/semantic/ex4.py:2:0 Unbound name [10]: Name `y` is used but not defined in the current scope.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "pyccel/pyccel",
    "commit": "40aab822dfedd645d5d611d7e7e16ef9121409fc",
    "filename": "tests/errors/semantic/ex5.py",
    "min_patch_found": false,
    "full_warning_msg": "tests/errors/semantic/ex5.py:1:9 Unbound name [10]: Name `a` is used but not defined in the current scope.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  }
]