[
  {
    "project": "tf-encrypted/tf-encrypted",
    "commit": "c9770301e28e8f7ef0931ab460f405673bf9af1b",
    "filename": "tensorflow_encrypted/training.py",
    "min_patch_found": false,
    "full_warning_msg": "tensorflow_encrypted/training.py:144:31 Unbound name [10]: Name `shape_x` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tf-encrypted-tf-encrypted/tensorflow_encrypted/training.py'",
    "dd_fail": true
  },
  {
    "project": "tf-encrypted/tf-encrypted",
    "commit": "c9770301e28e8f7ef0931ab460f405673bf9af1b",
    "filename": "tensorflow_encrypted/training.py",
    "min_patch_found": false,
    "full_warning_msg": "tensorflow_encrypted/training.py:144:40 Unbound name [10]: Name `num_batches` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tf-encrypted-tf-encrypted/tensorflow_encrypted/training.py'",
    "dd_fail": true
  },
  {
    "project": "tf-encrypted/tf-encrypted",
    "commit": "c9770301e28e8f7ef0931ab460f405673bf9af1b",
    "filename": "tensorflow_encrypted/training.py",
    "min_patch_found": false,
    "full_warning_msg": "tensorflow_encrypted/training.py:145:31 Unbound name [10]: Name `shape_y` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tf-encrypted-tf-encrypted/tensorflow_encrypted/training.py'",
    "dd_fail": true
  }
]