[
  {
    "project": "pytroll/satpy",
    "commit": "7e9389004e4c4ed17f8a5cf1555fe3aa949b1d07",
    "filename": "satpy/modifiers/angles.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/pytroll-satpy/satpy/modifiers/angles.py",
    "file_hunks_size": 4,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "satpy/modifiers/angles.py:280:41 Incompatible variable type [9]: chunks is declared to have type `int` but is used as type `str`.",
    "message": " chunks is declared to have type `int` but is used as type `str`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 280,
    "warning_line": "def _get_valid_lonlats(area: PRGeometry, chunks: int = \"auto\") -> tuple[da.Array, da.Array]:"
  }
]